# # Recommendation Program
from collections import deque
import time,os,sys



def typingPrint(text):
  for character in text:
    sys.stdout.write(character)
    sys.stdout.flush()
    time.sleep(0.05)





class QuestionNode:

    def __init__(self, question):
        self.question = question
        self.children = []

    def add_child(self, node):
        self.children.append(node)

rating1 = QuestionNode("First question. We need to make sure the movie we recommend is appropriate for all of the viewers. \n How old is the youngest member of your audience that will be watching? \n A. 17 years and over, we can handle anything. \n B. Between 16 to 13 years old, just no R movies please.  \n C. Between 12 to 8 years old, lets keep it PG. \n D. Under 8 years old, I need a movie for the whole family. \n Please type the corresponding letter here and hit ENTER: ")
times1 = QuestionNode("Next question, how much time do you have for a movie? \n A. I'm busy, keep it under 1.5 hours. \n B. Around 2 hours sounds good. \n C. I'm ready for a marathon! It should be at least 2.5 hours +. \n Please type the corresponding letter here and hit ENTER: ")
genre1 = QuestionNode("Which describes how you're feeling right now? \n A. I want to relax. \n B. I'm ready for soemthing more intense. \n Please type the corresponding letter here and hit ENTER: ")
genre2a = QuestionNode("Ok, you want a more relaxing movie. which of these would you prefer? \n A. I want something other worldly. \n B. I want something in this reality. \n Please type the corresponding letter here and hit ENTER: ")
genre2b = QuestionNode("Ok so you'd like something a little more intense. What sorts of things do you care more about in a movie? \n A. I care about characters and their relationships. \n B. I care about the setting and what's going on in the world. \n Please type the corresponding letter here and hit ENTER: ")
genre2bb = QuestionNode("Got it. One last question. Which would you prefer? \n A. I want to feel stressed with adrenaline.  \n B. Just a standard car chase and fight scene is all I need. \n Please type the corresponding letter here and hit ENTER: ")

class TreeNode:

    def __init__(self, title, rating, genre, duration, topic):
        self.title = title
        self.rating = rating
        self.duration = duration
        self.genre = genre
        self.topic = topic
        self.children = []

    def add_child(self, child_node):
        self.children.append(child_node)
        

movie1=TreeNode("The Shawshank Redemption","R","Drama","142","Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.")
movie2=TreeNode("The Godfather","R","Drama","175","The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son.")
movie3=TreeNode("The Dark Knight","PG-13","Drama;Crime","152","When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.")
movie4=TreeNode("The Godfather: Part II","R","Drama;Crime;Action","202","The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.")
movie5=TreeNode("12 Angry Men","PG","Drama;Crime","96","The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.")
movie6=TreeNode("Schindler's List","R","Drama;History;Biography","195","In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.")
movie7=TreeNode("The Lord of the Rings: The Return of the King","PG-13","Drama;Action;Adventure","201","Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.")
movie8=TreeNode("Pulp Fiction","R","Drama;Crime","154","The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.")
movie9=TreeNode("The Lord of the Rings: The Fellowship of the Ring","PG-13","Drama;Action;Adventure","178","A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.")
movie10=TreeNode("The Good, the Bad and the Ugly","R","Adventure;Western","178","A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.")
movie11=TreeNode("Forrest Gump","PG-13","Drama;Romance","142","The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.")
movie12=TreeNode("Fight Club","R","Drama","139","An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.")
movie13=TreeNode("Inception","PG-13","Action;Adventure;Sci-Fi","148","A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.")
movie14=TreeNode("The Lord of the Rings: The Two Towers","PG-13","Drama;Action;Adventure","179","While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.")
movie15=TreeNode("Star Wars: Episode V - The Empire Strikes Back","PG","Action;Adventure;Fantasy","124","After the Rebels are brutally overpowered by the Empire on the ice planet Hoth, Luke Skywalker begins Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.")
movie16=TreeNode("The Matrix","R","Action;Sci-Fi","136","When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.")
movie17=TreeNode("Goodfellas","R","Drama;Crime;Biography","145","The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.")
movie18=TreeNode("One Flew Over the Cuckoo's Nest","R","Drama","133","A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.")
movie19=TreeNode("Se7en","R","Drama;Crime;Mystery","127","Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.")
movie20=TreeNode("Seven Samurai","PG-13","Drama;Action","207","A veteran samurai, gathers six samurais to protect a village from the cruel bandits. As the samurais teach the natives how to defend themselves, the village is attacked by a pack of 40 bandits.")
movie21=TreeNode("It's a Wonderful Life","PG","Drama;Fantasy;Family","130","An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.")
movie22=TreeNode("The Silence of the Lambs","R","Drama;Crime;Thriller","118","A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.")
movie23=TreeNode("City of God","R","Drama;Crime","130","In the slums of Rio, two kids' paths diverge as one struggles to become a photographer and the other a kingpin.")
movie24=TreeNode("Saving Private Ryan","R","Drama;War","169","Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.")
movie25=TreeNode("Life Is Beautiful","PG-13","Drama;Romance;Comedy","116","When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.")
movie26=TreeNode("The Green Mile","R","Drama;Crime;Fantasy","189","The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.")
movie27=TreeNode("Interstellar","PG-13","Drama;Adventure;Sci-Fi","169","A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.")
movie28=TreeNode("Star Wars A New Hope","PG","Action;Adventure;Fantasy","121","Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.")
movie29=TreeNode("Terminator 2: Judgment Day","R","Action;Sci-Fi","137","A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her ten-year-old son John from a more advanced and powerful cyborg.")
movie30=TreeNode("Back to the Future","PG","Adventure;Comedy;Sci-Fi","116","Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.")
movie31=TreeNode("Spirited Away","PG","Adventure;Family;Animation","125","During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.")
movie32=TreeNode("Psycho","R","Mystery;Thriller;Horror","109","A Phoenix secretary embezzles $40,000 from her employer's client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.")
movie33=TreeNode("The Pianist","R","Drama;Biography;Music","150","A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.")
movie34=TreeNode("Léon: The Professional","R","Drama;Crime;Action","110","12-year-old Mathilda is reluctantly taken in by Léon, a professional assassin, after her family is murdered. An unusual relationship forms as she becomes his protégée and learns the assassin's trade.")
movie35=TreeNode("Parasite","R","Drama;Comedy;Thriller","132","Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.")
movie36=TreeNode("The Lion King","G","Drama;Adventure;Animation","88","Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.")
movie37=TreeNode("Gladiator","R","Drama;Action;Adventure","155","A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.")
movie38=TreeNode("American History X","R","Drama;Crime","119","A former neo-nazi skinhead tries to prevent his younger brother from going down the same wrong path that he did.")
movie39=TreeNode("The Usual Suspects","R","Drama;Crime;Mystery","106","A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.")
movie40=TreeNode("The Departed","R","Drama;Crime;Thriller","151","An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.")
movie41=TreeNode("The Prestige","PG-13","Drama;Mystery;Sci-Fi","130","After a tragic accident, two stage magicians in 1890s London engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.")
movie42=TreeNode("Casablanca","PG","Drama;Romance;War","102","A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.")
movie43=TreeNode("Whiplash","R","Drama;Music","106","A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.")
movie44=TreeNode("Top Gun: Maverick","PG-13","Drama;Action","130","After more than thirty years of service as one of the Navy's top aviators, Pete Mitchell is where he belongs, pushing the envelope as a courageous test pilot and dodging the advancement in rank that would ground him.")
movie45=TreeNode("The Intouchables","R","Drama;Biography;Comedy","112","After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.")
movie46=TreeNode("Modern Times","G","Drama;Romance;Comedy","87","The Tramp struggles to live in modern industrial society with the help of a young homeless woman.")
movie47=TreeNode("Hara-Kiri","R","Drama;Action;Mystery","133","When a ronin requesting seppuku at a feudal lord's palace is told of the brutal suicide of another ronin who previously visited, he reveals how their pasts are intertwined - and in doing so challenges the clan's integrity.")
movie48=TreeNode("Grave of the Fireflies","PG-13","Drama;War;Animation","89","A young boy and his little sister struggle to survive in Japan during World War II.")
movie49=TreeNode("Once Upon a Time in the West","PG-13","Western","165","A mysterious stranger with a harmonica joins forces with a notorious desperado to protect a beautiful widow from a ruthless assassin working for the railroad.")
movie50=TreeNode("Rear Window","PG","Mystery;Thriller","112","A wheelchair-bound photographer spies on his neighbors from his Greenwich Village courtyard apartment window, and becomes convinced one of them has committed murder, despite the skepticism of his fashion-model girlfriend.")
movie51=TreeNode("Alien","R","Sci-Fi;Horror","117","The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission.")
movie52=TreeNode("City Lights","G","Drama;Romance;Comedy","87","With the aid of a wealthy erratic tippler, a dewy-eyed tramp who has fallen in love with a sightless flower girl accumulates money to be able to help her medically.")
movie53=TreeNode("Cinema Paradiso","PG-13","Drama;Romance","155","A filmmaker recalls his childhood when falling in love with the pictures at the cinema of his home village and forms a deep friendship with the cinema's projectionist.")
movie54=TreeNode("Memento","R","Mystery;Thriller","113","A man with short-term memory loss attempts to track down his wife's murderer.")
movie55=TreeNode("Apocalypse Now","R","Drama;Mystery;War","147","A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.")
movie56=TreeNode("Indiana Jones and the Raiders of the Lost Ark","PG","Adventure;Action","115","In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain its awesome powers.")
movie57=TreeNode("Django Unchained","R","Drama;Western","165","With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.")
movie58=TreeNode("WALL·E","G","Adventure;Animation;Family","98","In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will ultimately decide the fate of mankind.")
movie59=TreeNode("The Lives of Others","R","Drama;Mystery;Thriller","137","In 1984 East Berlin, an agent of the secret police, conducting surveillance on a writer and his lover, finds himself becoming increasingly absorbed by their lives.")
movie60=TreeNode("Sunset Blvd.","PG","Drama;Film-Noir","110","A screenwriter develops a dangerous relationship with a faded film star determined to make a triumphant return.")
movie61=TreeNode("Paths of Glory","PG-13","Drama;War","88","After refusing to attack an enemy position, a general accuses the soldiers of cowardice and their commanding officer must defend them.")
movie62=TreeNode("The Shining","R","Drama;Horror","146","A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.")
movie63=TreeNode("The Great Dictator","G","Drama;Comedy;War","125","Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkel's regime.")
movie64=TreeNode("Witness for the Prosecution","PG-13","Drama;Crime;Mystery","116","A veteran British barrister must defend his client in a murder trial that has surprise after surprise.")
movie65=TreeNode("Avengers: Infinity War","PG-13","Action;Adventure;Sci-Fi","149","The Avengers and their allies must be willing to sacrifice all in an attempt to defeat the powerful Thanos before his blitz of devastation and ruin puts an end to the universe.")
movie66=TreeNode("Aliens","R","Action;Adventure;Sci-Fi","137","Fifty-seven years after surviving an apocalyptic attack aboard her space vessel by merciless space creatures, Officer Ripley awakens from hyper-sleep and tries to warn anyone who will listen about the predators.")
movie67=TreeNode("American Beauty","R","Drama","122","A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter's best friend.")
movie68=TreeNode("Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb","PG","Comedy;War","95","An insane American general orders a bombing attack on the Soviet Union, triggering a path to nuclear holocaust that a war room full of politicians and generals frantically tries to stop.")
movie69=TreeNode("Spider-Man: Into the Spider-Verse","PG","Action;Adventure;Animation","117","Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.")
movie70=TreeNode("The Dark Knight Rises","PG-13","Drama;Action","164","Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal guerrilla terrorist Bane.")
movie71=TreeNode("Oldboy","R","Drama;Action;Mystery","120","After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.")
movie72=TreeNode("Joker","R","Drama;Crime;Thriller","122","A mentally troubled stand-up comedian embarks on a downward spiral that leads to the creation of an iconic villain.")
movie73=TreeNode("Amadeus","PG-13","Drama;Biography;Music","160","The life, success and troubles of Wolfgang Amadeus Mozart, as told by Antonio Salieri, the contemporaneous composer who was insanely jealous of Mozart's talent and claimed to have murdered him.")
movie74=TreeNode("Braveheart","R","Drama;Biography;History","178","Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.")
movie75=TreeNode("Toy Story","G","Adventure;Comedy;Animation","81","A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's room.")
movie76=TreeNode("Coco","PG","Adventure;Comedy;Animation","105","Aspiring musician Miguel, confronted with his family's ancestral ban on music, enters the Land of the Dead to find his great-great-grandfather, a legendary singer.")
movie77=TreeNode("The Boat","R","Drama;War","149","The claustrophobic world of a WWII German U-boat; boredom, filth and sheer terror.")
movie78=TreeNode("Inglourious Basterds","R","Drama;Adventure;War","153","In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.")
movie79=TreeNode("Princess Mononoke","PG-13","Adventure;Animation;Fantasy","134","On a journey to find the cure for a Tatarigami's curse, Ashitaka finds himself in the middle of a war between the forest gods and Tatara, a mining colony. In this quest he also meets San, the Mononoke Hime.")
movie80=TreeNode("Avengers: Endgame","PG-13","Drama;Adventure;Action","181","After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.")
movie81=TreeNode("Once Upon a Time in America","R","Drama;Crime","229","A former Prohibition-era Jewish gangster returns to the Lower East Side of Manhattan 35 years later, where he must once again confront the ghosts and regrets of his old life.")
movie82=TreeNode("Good Will Hunting","R","Drama;Romance","126","Will Hunting, a janitor at M.I.T., has a gift for mathematics, but needs help from a psychologist to find direction in his life.")
movie83=TreeNode("Toy Story 3","G","Adventure;Animation;Comedy","103","The toys are mistakenly delivered to a day-care center instead of the attic right before Andy leaves for college, and it's up to Woody to convince the other toys that they weren't abandoned and to return home.")
movie84=TreeNode("Requiem for a Dream","R","Drama","102","The drug-induced utopias of four Coney Island people are shattered when their addictions run deep.")
movie85=TreeNode("Your Name.","PG","Drama;Animation;Fantasy","106","Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?")
movie86=TreeNode("Singin' in the Rain","G","Comedy;Romance;Musical","103","A silent film star falls for a chorus girl just as he and his delusionally jealous screen partner are trying to make the difficult transition to talking pictures in 1920s Hollywood.")
movie87=TreeNode("3 Idiots","PG-13","Drama;Comedy","170","Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently, even as the rest of the world called them idiots.")
movie88=TreeNode("Star Wars: Episode VI - Return of the Jedi","PG","Action;Adventure;Fantasy","131","After a daring mission to rescue Han Solo from Jabba the Hutt, the Rebels dispatch to Endor to destroy the second Death Star. Meanwhile, Luke struggles to help Darth Vader back from the dark side without falling into the Emperor's trap.")
movie89=TreeNode("2001: A Space Odyssey","G","Adventure;Sci-Fi","149","After uncovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter to find its origins - a spacecraft manned by two men and the supercomputer H.A.L. 9000.")
movie90=TreeNode("Eternal Sunshine of the Spotless Mind","R","Drama;Romance;Sci-Fi","108","When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.")
movie91=TreeNode("Reservoir Dogs","R","Drama;Crime;Thriller","99","When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.")
movie92=TreeNode("High and Low","PG-13","Drama;Crime;Mystery","143","An executive of a Yokohama shoe company becomes a victim of extortion when his chauffeur's son is kidnapped by mistake and held for ransom.")
movie93=TreeNode("Capernaum","R","Drama","126","While serving a five-year sentence for a violent crime, a 12-year-old boy sues his parents for neglect.")
movie94=TreeNode("Citizen Kane","PG","Drama;Mystery","119","Following the death of publishing tycoon Charles Foster Kane, reporters scramble to uncover the meaning of his final utterance: 'Rosebud.'")
movie95=TreeNode("Lawrence of Arabia","PG","Drama;Adventure;Biography","218","The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I in order to fight the Turks.")
movie96=TreeNode("The Hunt","R","Drama","115","A teacher lives a lonely life, all the while struggling over his son's custody. His life slowly gets better as he finds love and receives good news from his son, but his new luck is about to be brutally shattered by an innocent little lie.")
movie97=TreeNode("M","PG-13","Crime;Mystery;Thriller","99","When the police in a German city are unable to catch a child-murderer, other criminals join in the manhunt.")
movie98=TreeNode("North by Northwest","PG-13","Adventure;Action;Mystery","136","A New York City advertising executive goes on the run after being mistaken for a government agent by a group of foreign spies, and falls for a woman whose loyalties he begins to doubt.")
movie99=TreeNode("Vertigo","PG","Romance;Mystery;Thriller","128","A former San Francisco police detective juggles wrestling with his personal demons and becoming obsessed with the hauntingly beautiful woman he has been hired to trail, who may be deeply disturbed.")
movie100=TreeNode("Amélie","R","Comedy;Romance","122","Amélie is an innocent and naive girl in Paris with her own sense of justice. She decides to help those around her and, along the way, discovers love.")
movie101=TreeNode("A Clockwork Orange","R","Crime;Sci-Fi","136","In the future, a sadistic gang leader is imprisoned and volunteers for a conduct-aversion experiment, but it doesn't go as planned.")
movie102=TreeNode("Come and See","R","Drama;Thriller;War","142","After finding an old rifle, a young boy joins the Soviet resistance movement against ruthless German forces and experiences the horrors of World War II.")
movie103=TreeNode("Full Metal Jacket","R","Drama;War","116","A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.")
movie104=TreeNode("Double Indemnity","PG","Drama;Crime;Film-Noir","107","A Los Angeles insurance representative lets an alluring housewife seduce him into a scheme of insurance fraud and murder that arouses the suspicion of his colleague, an insurance investigator.")
movie105=TreeNode("The Apartment","PG-13","Drama;Romance;Comedy","125","A Manhattan insurance clerk tries to rise in his company by letting its executives use his apartment for trysts, but complications and a romance of his own ensue.")
movie106=TreeNode("Scarface","R","Drama;Crime","170","In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.")
movie107=TreeNode("Ikiru","PG-13","Drama","143","A bureaucrat tries to find meaning in his life after he discovers he has terminal cancer.")
movie108=TreeNode("The Sting","PG","Drama;Crime;Comedy","129","Two grifters team up to pull off the ultimate con.")
movie109=TreeNode("To Kill a Mockingbird","PG-13","Drama;Crime","129","Atticus Finch, a widowed lawyer in Depression-era Alabama, defends a black man against an undeserved rape charge, and his children against prejudice.")
movie110=TreeNode("Taxi Driver","R","Drama;Crime","114","A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.")
movie111=TreeNode("L.A. Confidential","R","Drama;Crime;Mystery","138","As corruption grows in 1950s Los Angeles, three policemen - one strait-laced, one brutal, and one sleazy - investigate a series of murders with their own brand of justice.")
movie112=TreeNode("Up","PG","Adventure;Comedy;Animation","96","78-year-old Carl Fredricksen travels to Paradise Falls in his house equipped with balloons, inadvertently taking a young stowaway.")
movie113=TreeNode("Heat","R","Drama;Crime;Action","170","A group of high-end professional thieves start to feel the heat from the LAPD when they unknowingly leave a clue at their latest heist.")
movie114=TreeNode("Metropolis","PG-13","Drama;Sci-Fi","153","In a futuristic city sharply divided between the working class and the city planners, the son of the city's mastermind falls in love with a working-class prophet who predicts the coming of a savior to mediate their differences.")
movie115=TreeNode("Hamilton","PG-13","Drama;Biography;History","160","The real life of one of America's foremost founding fathers and first Secretary of the Treasury, Alexander Hamilton. Captured live on Broadway from the Richard Rodgers Theater with the original Broadway cast.")
movie116=TreeNode("A Separation","R","Drama","123","A married couple are faced with a difficult decision - to improve the life of their child by moving to another country or to stay in Iran and look after a deteriorating parent who has Alzheimer's disease.")
movie117=TreeNode("Snatch","R","Crime;Comedy","102","Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.")
movie118=TreeNode("Die Hard","R","Action;Thriller","132","An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.")
movie119=TreeNode("Incendies","R","Drama;Mystery","131","Twins journey to the Middle East to discover their family history and fulfill their mother's last wishes.")
movie120=TreeNode("Indiana Jones and the Last Crusade","PG","Action;Adventure","127","In 1938, after his father Professor Henry Jones, Sr. goes missing while pursuing the Holy Grail, Professor Henry Indiana Jones, Jr. finds himself up against Adolf Hitler's Nazis again to stop them from obtaining its powers.")
movie121=TreeNode("Bicycle Thieves","PG-13","Drama","89","In post-war Italy, a working-class man's bicycle is stolen, endangering his efforts to find work. He and his son set out to find it.")
movie122=TreeNode("1917","R","Drama;Action;War","119","April 6th, 1917. As an infantry battalion assembles to wage war deep in enemy territory, two soldiers are assigned to race against time and deliver a message that will stop 1,600 men from walking straight into a deadly trap.")
movie123=TreeNode("Like Stars on Earth","PG","Drama;Family","165","An eight-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.")
movie124=TreeNode("Spider-Man: No Way Home","PG","Action;Adventure;Fantasy","148","With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.")
movie125=TreeNode("Downfall","R","Drama;History;Biography","156","Traudl Junge, the final secretary for Adolf Hitler, tells of the Nazi dictator's final days in his Berlin bunker at the end of WWII.")
movie126=TreeNode("For a Few Dollars More","R","Western","132","Two bounty hunters with the same intentions team up to track down an escaped Mexican outlaw.")
movie127=TreeNode("Batman Begins","PG-13","Drama;Crime;Action","140","After training with his mentor, Batman begins his fight to free crime-ridden Gotham City from corruption.")
movie128=TreeNode("Dangal","PG-13","Drama;Action;Biography","161","Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.")
movie129=TreeNode("The Kid","PG","Drama;Comedy;Family","68","The Tramp cares for an abandoned child, but events put their relationship in jeopardy.")
movie130=TreeNode("Some Like It Hot","PG-13","Romance;Comedy;Music","121","After two male musicians witness a mob hit, they flee the state in an all-female band disguised as women, but further complications set in.")
movie131=TreeNode("The Father","PG-13","Drama;Mystery","97","A man refuses all assistance from his daughter as he ages. As he tries to make sense of his changing circumstances, he begins to doubt his loved ones, his own mind and even the fabric of his reality.")
movie132=TreeNode("All About Eve","PG-13","Drama","138","A seemingly timid but secretly ruthless ingénue insinuates herself into the lives of an aging Broadway star and her circle of theater friends.")
movie133=TreeNode("Green Book","PG-13","Drama;Comedy;Biography","130","A working-class Italian-American bouncer becomes the driver for an African-American classical pianist on a tour of venues through the 1960s American South.")
movie134=TreeNode("The Wolf of Wall Street","R","Biography;Comedy;Crime","180","Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.")
movie135=TreeNode("Judgment at Nuremberg","Pg-13","Drama;War","179","In 1948, an American court in occupied Germany tries four Nazis judged for war crimes.")
movie136=TreeNode("Unforgiven","R","Drama;Western","130","Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young man, The Schofield Kid.")
movie137=TreeNode("Ran","R","Drama;Action;War","162","In Medieval Japan, an elderly warlord retires, handing over his empire to his three sons. However, he vastly underestimates how the new-found power will corrupt them and cause them to turn on each other...and him.")
movie138=TreeNode("Casino","R","Drama;Crime","178","A tale of greed, deception, money, power, and murder occur between two best friends: a mafia enforcer and a casino executive compete against each other over a gambling empire, and over a fast-living and fast-loving socialite.")
movie139=TreeNode("Pan's Labyrinth","R","Drama;Fantasy;War","118","")
movie140=TreeNode("There Will Be Blood","R","Drama","158","A story of family, religion, hatred, oil and madness, focusing on a turn-of-the-century prospector in the early days of the business.")
movie141=TreeNode("Everything Everywhere All at Once","R","Action;Adventure;Comedy","139","An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led.")
movie142=TreeNode("The Sixth Sense","PG-13","Drama;Mystery;Thriller","107","A frightened, withdrawn Philadelphia boy who communicates with spirits seeks the help of a disheartened child psychologist.")
movie143=TreeNode("A Beautiful Mind","PG-13","Drama;Biography","135","After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the nightmarish.")
movie144=TreeNode("Monty Python and the Holy Grail","PG","Adventure;Comedy;Fantasy","91","King Arthur and his Knights of the Round Table embark on a surreal, low-budget search for the Holy Grail, encountering many, very silly obstacles.")
movie145=TreeNode("The Truman Show","PG","Drama;Comedy","103","An insurance salesman discovers his whole life is actually a reality TV show.")
movie146=TreeNode("Yojimbo","PG-13","Drama;Action;Thriller","110","A crafty ronin comes to a town divided by two criminal gangs and decides to play them against each other to free the town.")
movie147=TreeNode("The Treasure of the Sierra Madre","PG-13","Drama;Adventure;Western","126","Two down-on-their-luck Americans searching for work in 1920s Mexico convince an old prospector to help them mine for gold in the Sierra Madre Mountains.")
movie148=TreeNode("Shutter Island","R","Mystery;Thriller","138","In 1954, a U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.")
movie149=TreeNode("Rashomon","PG-13","Drama;Crime;Mystery","88","The rape of a bride and the murder of her samurai husband are recalled from the perspectives of a bandit, the bride, the samurai's ghost and a woodcutter.")
movie150=TreeNode("Jurassic Park","PG-13","Action;Adventure;Sci-Fi","127","A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.")
movie151=TreeNode("The Great Escape","PG","Drama;Adventure;History","172","Allied prisoners of war plan for several hundred of their number to escape from a German camp during World War II.")
movie152=TreeNode("Kill Bill: Vol. 1","R","Drama;Action;Crime","111","After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.")
movie153=TreeNode("No Country for Old Men","R","Drama;Crime;Thriller","122","Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.")
movie154=TreeNode("Finding Nemo","G","Adventure;Comedy;Animation","100","After his son is captured in the Great Barrier Reef and taken to Sydney, a timid clownfish sets out on a journey to bring him home.")
movie155=TreeNode("The Elephant Man","PG","Drama;Biography","124","A Victorian surgeon rescues a heavily disfigured man who is mistreated while scraping a living as a side-show freak. Behind his monstrous façade, there is revealed a person of kindness, intelligence and sophistication.")
movie156=TreeNode("Chinatown","R","Drama;Mystery;Thriller","130","A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder.")
movie157=TreeNode("Raging Bull","R","Drama;Biography;Sport","129","The life of boxer Jake LaMotta, whose violence and temper that led him to the top in the ring destroyed his life outside of it.")
movie158=TreeNode("Gone with the Wind","PG-13","Drama;Romance;War","238","The manipulative daughter of a Georgia plantation owner conducts a turbulent romance with a roguish profiteer during the American Civil War and Reconstruction periods.")
movie159=TreeNode("V for Vendetta","R","Drama;Action;Sci-Fi","132","In a future British dystopian society, a shadowy freedom fighter, known only by the alias of V, plots to overthrow the tyrannical government - with the help of a young woman.")
movie160=TreeNode("The Thing","R","Sci-Fi;Mystery;Horror","109","A research team in Antarctica is hunted by a shape-shifting alien that assumes the appearance of its victims.")
movie161=TreeNode("Inside Out","PG","Adventure;Comedy;Animation","95","After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions - Joy, Fear, Anger, Disgust and Sadness - conflict on how best to navigate a new city, house, and school.")
movie162=TreeNode("Lock, Stock and Two Smoking Barrels","R","Action;Crime;Comedy","107","Eddy persuades his three pals to pool money for a vital poker game against a powerful local mobster, Hatchet Harry. Eddy loses, after which Harry gives him a week to pay back 500,000 pounds.")
movie163=TreeNode("Dial M for Murder","PG","Crime;Thriller","105","A former tennis star arranges the murder of his adulterous wife.")
movie164=TreeNode("The Secret in Their Eyes","PG-13","Drama;Romance;Mystery","129","A retired legal counselor writes a novel hoping to find closure for one of his past unresolved homicide cases and for his unreciprocated love with his superior - both of which still haunt him decades later.")
movie165=TreeNode("Howl's Moving Castle","PG","Adventure;Family;Animation","119","When an unconfident young woman is cursed with an old body by a spiteful witch, her only chance of breaking the spell lies with a self-indulgent yet insecure young wizard and his companions in his legged, walking castle.")
movie166=TreeNode("The Bridge on the River Kwai","PG","Drama;Adventure;War","161","British POWs are forced to build a railway bridge across the river Kwai for their Japanese captors in occupied Burma, not knowing that the allied forces are planning a daring commando raid through the jungle to destroy it.")
movie167=TreeNode("Three Billboards Outside Ebbing, Missouri","R","Drama;Crime;Comedy","115","A mother personally challenges the local authorities to solve her daughter's murder when they fail to catch the culprit.")
movie168=TreeNode("Trainspotting","R","Drama","93","Renton, deeply immersed in the Edinburgh drug scene, tries to clean up and get out, despite the allure of the drugs and influence of friends.")
movie169=TreeNode("Warrior","PG-13","Drama;Action;Sport","140","")
movie170=TreeNode("Gran Torino","R","Drama","116","Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, Thao Lor, a Hmong teenager who tried to steal Kowalski's prized possession: a 1972 Gran Torino.")
movie171=TreeNode("Fargo","R","Crime;Thriller","98","Minnesota car salesman Jerry Lundegaard's inept crime falls apart due to his and his henchmen's bungling and the persistent police work of the quite pregnant Marge Gunderson.")
movie172=TreeNode("Prisoners","R","Drama;Crime;Mystery","153","When Keller Dover's daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts.")
movie173=TreeNode("My Neighbor Totoro","G","Comedy;Animation;Family","86","When two girls move to the country to be near their ailing mother, they have adventures with the wondrous forest spirits who live nearby.")
movie174=TreeNode("Million Dollar Baby","PG-13","Drama;Sport","132","A determined woman works with a hardened boxing trainer to become a professional.")
movie175=TreeNode("The Gold Rush","PG-13","Drama;Comedy;Adventure","95","A prospector goes to the Klondike during the 1890s gold rush in hopes of making his fortune, and is smitten with a girl he sees in a dance hall.")
movie176=TreeNode("Blade Runner","R","Drama;Action;Sci-Fi","117","A blade runner must pursue and terminate four replicants who stole a ship in space, and have returned to Earth to find their creator.")
movie177=TreeNode("Catch Me If You Can","PG-13","Drama;Biography;Crime","141","Barely 21 yet, Frank is a skilled forger who has passed as a doctor, lawyer and pilot. FBI agent Carl becomes obsessed with tracking down the con man, who only revels in the pursuit.")
movie178=TreeNode("On the Waterfront","PG","Drama;Crime;Thriller","108","An ex-prize fighter turned New Jersey longshoreman struggles to stand up to his corrupt union bosses, including his older brother, as he starts to connect with the grieving sister of one of the syndicate's victims.")
movie179=TreeNode("The Third Man","PG-13","Mystery;Thriller;Film-Noir","93","Pulp novelist Holly Martins travels to shadowy, postwar Vienna, only to find himself investigating the mysterious death of an old friend, Harry Lime.")
movie180=TreeNode("Children of Heaven","PG","Drama;Family;Sport","89","After a boy loses his sister's pair of shoes, he goes on a series of adventures in order to find them. When he can't, he tries a new way to win a new pair.")
movie181=TreeNode("Ben-Hur","G","Drama;Adventure;History","212","After a Jewish prince is betrayed and sent into slavery by a Roman friend in 1st-century Jerusalem, he regains his freedom and comes back for revenge.")
movie182=TreeNode("12 Years a Slave","R","Drama;History;Biography","134","In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.")
movie183=TreeNode("The General","R","Action;Adventure;Comedy","67","After being rejected by the Confederate military, not realizing it was due to his crucial civilian role, an engineer must single-handedly recapture his beloved locomotive after it is seized by Union spies and return it through enemy lines.")
movie184=TreeNode("Wild Strawberries","PG","Drama;Romance","91","After living a life marked by coldness, an aging professor is forced to confront the emptiness of his existence.")
movie185=TreeNode("Before Sunrise","R","Drama;Romance","101","A young man and woman meet on a train in Europe, and wind up spending one evening together in Vienna. Unfortunately, both know that this will probably be their only night together.")
movie186=TreeNode("Gone Girl","R","Drama;Mystery;Thriller","149","With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him when it's suspected that he may not be innocent.")
movie187=TreeNode("Harry Potter and the Deathly Hallows: Part 2","PG-13","Adventure;Fantasy;Mystery","130","Harry, Ron, and Hermione search for Voldemort's remaining Horcruxes in their effort to destroy the Dark Lord as the final battle rages on at Hogwarts.")
movie188=TreeNode("The Deer Hunter","R","Drama;War","183","An in-depth examination of the ways in which the Vietnam War impacts and disrupts the lives of several friends in a small steel mill town in Pennsylvania.")
movie189=TreeNode("In the Name of the Father","R","Drama;Biography;Crime","133","A man's coerced confession to an I.R.A. bombing he did not commit results in the imprisonment of his father as well. An English lawyer fights to free them.")
movie190=TreeNode("The Grand Budapest Hotel","R","Adventure;Crime;Comedy","99","A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy in the hotel's glorious years under an exceptional concierge.")
movie191=TreeNode("Mr. Smith Goes to Washington","G","Drama;Comedy","129","A naive youth leader is appointed to fill a vacancy in the U.S. Senate. His idealistic plans promptly collide with corruption at home and subterfuge from his hero in Washington, but he tries to forge ahead despite attacks on his character.")
movie192=TreeNode("The Wages of Fear","PG","Drama;Adventure;Thriller","131","In a decrepit South American village, four men are hired to transport an urgent nitroglycerine shipment without the equipment that would make it safe.")
movie193=TreeNode("Barry Lyndon","PG","Adventure;Drama;War","185","An Irish rogue wins the heart of a rich widow and assumes her dead husband's aristocratic position in 18th-century England.")
movie194=TreeNode("Sherlock Jr.","PG-13","Action;Comedy;Romance","64800","A film projectionist longs to be a detective, and puts his meagre skills to work when he is framed by a rival for stealing his girlfriend's father's pocketwatch.")
movie195=TreeNode("Memories of Murder","R","Drama;Crime;Mystery","132","In a small Korean province in 1986, two detectives struggle with the case of multiple young women being found raped and murdered by an unknown culprit.")
movie196=TreeNode("Klaus","PG","Adventure;Comedy;Animation","96","A simple act of kindness always sparks another, even in a frozen, faraway place. When Smeerensburg's new postman, Jesper, befriends toymaker Klaus, their gifts melt an age-old feud and deliver a sleigh full of holiday traditions.")
movie197=TreeNode("Hacksaw Ridge","R","Drama;Biography;History","139","World War II American Army Medic Desmond T. Doss, who served during the Battle of Okinawa, refuses to kill people and becomes the first man in American history to receive the Medal of Honor without firing a shot.")
movie198=TreeNode("Room","R","Drama;Thriller","118","Held captive for 7 years in an enclosed space, a woman and her young son finally gain their freedom, allowing the boy to experience the outside world for the first time.")
movie199=TreeNode("The Seventh Seal","PG","Drama;Fantasy","96","A knight returning to Sweden after the Crusades seeks answers about life, death, and the existence of God as he plays chess against the Grim Reaper during the Black Plague.")
movie200=TreeNode("Wild Tales","R","Drama;Comedy;Thriller","122","Six short stories that explore the extremities of human behavior involving people in distress.")
movie201=TreeNode("The Big Lebowski","R","Crime;Comedy","117","Ultimate L.A. slacker Jeff The Dude Lebowski, mistaken for a millionaire of the same name, seeks restitution for a rug ruined by debt collectors, enlisting his bowling buddies for help while trying to find the millionaire's missing wife.")
movie202=TreeNode("Mad Max: Fury Road","R","Action;Adventure;Sci-Fi","120","In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.")
movie203=TreeNode("How to Train Your Dragon","PG","Action;Adventure;Animation","98","A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself, and learns there may be more to the creatures than he assumed.")
movie204=TreeNode("Mary and Max","R","Drama;Comedy;Animation","92","A tale of friendship between two unlikely pen pals: Mary, a lonely, eight-year-old girl living in the suburbs of Melbourne, and Max, a forty-four-year old, severely obese man living in New York.")
movie205=TreeNode("Monsters, Inc.","G","Adventure;Comedy;Animation","92","In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, two monsters realize things may not be what they think.")
movie206=TreeNode("Jaws","PG","Adventure;Thriller","124","When a killer shark unleashes chaos on a beach community off Long Island, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.")
movie207=TreeNode("The Passion of Joan of Arc","PG","Drama;Biography;History","114","In 1431, Jeanne d'Arc is placed on trial on charges of heresy. The ecclesiastical jurists attempt to force Jeanne to recant her claims of holy visions.")
movie208=TreeNode("Hotel Rwanda","PG-13","Drama;Biography;History","121","Paul Rusesabagina, a hotel manager, houses over a thousand Tutsi refugees during their struggle against the Hutu militia in Rwanda, Africa.")
movie209=TreeNode("Dead Poets Society","PG","Drama;Comedy","128","Maverick teacher John Keating uses poetry to embolden his boarding school students to new heights of self-expression.")
movie210=TreeNode("Tokyo Story","PG-13","Drama","136","An old couple visit their children and grandchildren in the city, but receive little attention.")
movie211=TreeNode("Pather Panchali","PG-13","Drama","125","Impoverished priest Harihar Ray, dreaming of a better life for himself and his family, leaves his rural Bengal village in search of work.")
movie212=TreeNode("Rocky","PG","Drama;Sport","120","A small-time Philadelphia boxer gets a supremely rare chance to fight the world heavyweight champion in a bout in which he strives to go the distance for his self-respect.")
movie213=TreeNode("Platoon","R","Drama;War","120","Chris Taylor, a neophyte recruit in Vietnam, finds himself caught in a battle of wills between two sergeants, one good and the other evil. A shrewd examination of the brutality of war and the duality of man in conflict.")
movie214=TreeNode("Ford v Ferrari","PG-13","Drama;Action;Biography","152","American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.")
movie215=TreeNode("Stand by Me","R","Drama;Adventure","89","After the death of one of his friends, a writer recounts a childhood journey with his friends to find the body of a missing boy.")
movie216=TreeNode("The Terminator","R","Action;Sci-Fi","107","A human soldier is sent from 2029 to 1984 to stop an almost indestructible cyborg killing machine, sent from the same year, which has been programmed to execute a young woman whose unborn son is the key to humanity's future salvation.")
movie217=TreeNode("Spotlight","R","Drama;Crime;Biography","129","The true story of how the Boston Globe uncovered the massive scandal of child molestation and cover-up within the local Catholic Archdiocese, shaking the entire Catholic Church to its core.")
movie218=TreeNode("Rush","R","Drama;Action;Biography","123","The merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda.")
movie219=TreeNode("Network","R","Drama","121","A television network cynically exploits a deranged former anchor's ravings and revelations about the news media for its own profit, but finds that his message may be difficult to control.")
movie220=TreeNode("Into the Wild","R","Drama;Adventure;Biography","148","After graduating from Emory University, top student and athlete Christopher McCandless abandons his possessions, gives his entire $24,000 savings account to charity and hitchhikes to Alaska to live in the wilderness. Along the way, Christopher encounters a series of characters that shape his life.")
movie221=TreeNode("Logan","R","Drama;Action;Sci-Fi","137","In a future where mutants are nearly extinct, an elderly and weary Logan leads a quiet life. But when Laura, a mutant child pursued by scientists, comes to him for help, he must get her to safety.")
movie222=TreeNode("The Wizard of Oz","PG","Adventure;Family;Fantasy","102","Young Dorothy Gale and her dog are swept away by a tornado from their Kansas farm to the magical Land of Oz, and embark on a quest with three new friends to see the Wizard, who can return her to her home and fulfill the others' wishes.")
movie223=TreeNode("Ratatouille","G","Adventure;Comedy;Animation","111","A rat who can cook makes an unusual alliance with a young kitchen worker at a famous Paris restaurant.")
movie224=TreeNode("Groundhog Day","PG","Drama;Comedy;Fantasy","101","A self-centered Pittsburgh weatherman finds himself inexplicably trapped in a small town as he lives the same day over and over again.")
movie225=TreeNode("Before Sunset","R","Drama;Romance","80","Nine years after Jesse and Celine first met, they encounter each other again on the French leg of Jesse's book tour.")
movie226=TreeNode("The Exorcist","R","Horror","122","When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.")
movie227=TreeNode("The Best Years of Our Lives","PG","Drama;Romance;War","170","Three World War II veterans, two of them traumatized or disabled, return home to the American midwest to discover that they and their families have been irreparably changed.")
movie228=TreeNode("The Incredibles","PG","Action;Adventure;Animation","115","While trying to lead a quiet suburban life, a family of undercover superheroes are forced into action to save the world.")
movie229=TreeNode("To Be or Not to Be","PG","Comedy;Romance;War","99","During the Nazi occupation of Poland, an acting troupe becomes embroiled in a Polish soldier's efforts to track down a German spy.")
movie230=TreeNode("The Battle of Algiers","R","Drama;War","121","In the 1950s, fear and violence escalate as the people of Algiers fight for independence from the French government.")
movie231=TreeNode("Rebecca","PG-13","Drama;Mystery;Film-Noir","130","A self-conscious woman juggles adjusting to her new role as an aristocrat's wife and avoiding being intimidated by his first wife's spectral presence.")
movie232=TreeNode("The Grapes of Wrath","G","Drama","129","An Oklahoma family, driven off their farm by the poverty and hopelessness of the Dust Bowl, joins the westward migration to California, suffering the misfortunes of the homeless in the Great Depression.")
movie233=TreeNode("Hachi: A Dog's Tale","G","Drama;Biography;Family","93","A college professor bonds with an abandoned dog he takes into his home.")
movie234=TreeNode("Cool Hand Luke","PG","Drama;Crime","127","A laid back Southern man is sentenced to two years in a rural prison, but refuses to conform.")
movie235=TreeNode("Amores perros","R","Drama;Thriller","154","A horrific car accident connects three stories, each involving characters dealing with loss, regret, and life's harsh realities, all in the name of love.")
movie236=TreeNode("Pirates of the Caribbean: The Curse of the Black Pearl","PG-13","Action;Adventure;Fantasy","143","Blacksmith Will Turner teams up with eccentric pirate Captain Jack Sparrow to save his love, the governor's daughter, from Jack's former pirate allies, who are now undead.")
movie237=TreeNode("La Haine","R","Drama;Crime","98","24 hours in the lives of three young men in the French suburbs the day after a violent riot.")
movie238=TreeNode("The 400 Blows","PG","Drama;Crime","99","A young boy, left without attention, delves into a life of petty crime.")
movie239=TreeNode("Persona","PG-13","Drama;Thriller","83","A nurse is put in charge of a mute actress and finds that their personae are melding together.")
movie240=TreeNode("My Father and My Son","PG-13","Drama;Family","112","The family of a left-wing journalist is torn apart after the military coup of Turkey in 1980.")
movie241=TreeNode("Life of Brian","R","Comedy","94","Born on the original Christmas in the stable next door to Jesus Christ, Brian of Nazareth spends his life being mistaken for a messiah.")
movie242=TreeNode("It Happened One Night","PG","Romance;Comedy","105","A renegade reporter trailing a young runaway heiress for a big story joins her on a bus heading from Florida to New York, and they end up stuck with each other when the bus leaves them behind at one of the stops.")
movie243=TreeNode("The Sound of Music","G","Drama;Biography;Family","172","A young novitiate is sent by her convent in 1930s Austria to become a governess to the seven children of a widowed naval officer.")
movie244=TreeNode("Dersu Uzala","G","Drama;Adventure;Biography","142","The Russian army sends an explorer on an expedition to the snowy Siberian wilderness where he makes friends with a seasoned local hunter.")
movie245=TreeNode("The Handmaiden","R","Drama;Romance;Thriller","145","A woman is hired as a handmaiden to a Japanese heiress, but secretly she is involved in a plot to defraud her.")
movie246=TreeNode("Aladdin","PG","Adventure;Comedy;Animation","90","A kindhearted street urchin and a power-hungry Grand Vizier vie for a magic lamp that has the power to make their deepest wishes come true.")
movie247=TreeNode("Gandhi","PG","Drama;Biography","191","The life of the lawyer who became the famed leader of the Indian revolts against the British rule through his philosophy of nonviolent protest.")
movie248=TreeNode("Jai Bhim","R","Drama;Crime;Mystery","164","When a tribal man is arrested for a case of alleged theft, his wife turns to a human-rights lawyer to help bring justice.")
movie249=TreeNode("The Help","PG-13","Drama","146","An aspiring author during the civil rights movement of the 1960s decides to write a book detailing the African American maids' point of view on the white families for which they work, and the hardships they go through on a daily basis.")
movie250=TreeNode("Beauty and the Beast","PG","Fantasy;Family;Animation","84","A prince cursed to spend his days as a hideous monster sets out to regain his humanity by earning a young woman's love.")




movie1.add_child(movie2)
movie1.add_child(movie3)
movie2.add_child(movie4)
movie2.add_child(movie5)
movie3.add_child(movie6)
movie3.add_child(movie7)
movie4.add_child(movie8)
movie4.add_child(movie9)
movie5.add_child(movie10)
movie5.add_child(movie11)
movie5.add_child(movie12)
movie6.add_child(movie13)
movie6.add_child(movie14)
movie7.add_child(movie15)
movie7.add_child(movie16)
movie8.add_child(movie17)
movie8.add_child(movie18)
movie9.add_child(movie19)
movie9.add_child(movie20)
movie10.add_child(movie21)
movie10.add_child(movie22)
movie11.add_child(movie23)
movie11.add_child(movie24)
movie11.add_child(movie25)
movie12.add_child(movie26)
movie12.add_child(movie27)
movie13.add_child(movie28)
movie13.add_child(movie29)
movie14.add_child(movie30)
movie14.add_child(movie31)
movie15.add_child(movie32)
movie15.add_child(movie33)
movie16.add_child(movie34)
movie16.add_child(movie35)
movie17.add_child(movie36)
movie17.add_child(movie37)
movie18.add_child(movie38)
movie18.add_child(movie39)
movie19.add_child(movie40)
movie19.add_child(movie41)
movie20.add_child(movie42)
movie20.add_child(movie43)
movie21.add_child(movie44)
movie21.add_child(movie45)
movie22.add_child(movie46)
movie22.add_child(movie47)
movie23.add_child(movie48)
movie23.add_child(movie49)
movie24.add_child(movie50)
movie24.add_child(movie51)
movie25.add_child(movie52)
movie25.add_child(movie53)
movie26.add_child(movie54)
movie26.add_child(movie55)
movie26.add_child(movie56)
movie27.add_child(movie57)
movie27.add_child(movie58)
movie28.add_child(movie59)
movie28.add_child(movie60)
movie29.add_child(movie61)
movie29.add_child(movie62)
movie30.add_child(movie63)
movie30.add_child(movie64)
movie31.add_child(movie65)
movie31.add_child(movie66)
movie32.add_child(movie67)
movie32.add_child(movie68)
movie33.add_child(movie69)
movie33.add_child(movie70)
movie34.add_child(movie71)
movie34.add_child(movie72)
movie35.add_child(movie73)
movie35.add_child(movie74)
movie36.add_child(movie75)
movie36.add_child(movie76)
movie37.add_child(movie77)
movie37.add_child(movie78)
movie38.add_child(movie79)
movie38.add_child(movie80)
movie39.add_child(movie81)
movie39.add_child(movie82)
movie40.add_child(movie83)
movie40.add_child(movie84)
movie41.add_child(movie85)
movie41.add_child(movie86)
movie42.add_child(movie87)
movie42.add_child(movie88)
movie42.add_child(movie89)
movie43.add_child(movie90)
movie43.add_child(movie91)
movie44.add_child(movie92)
movie44.add_child(movie93)
movie45.add_child(movie94)
movie45.add_child(movie95)
movie46.add_child(movie96)
movie46.add_child(movie97)
movie47.add_child(movie98)
movie47.add_child(movie99)
movie48.add_child(movie100)
movie48.add_child(movie101)
movie49.add_child(movie102)
movie49.add_child(movie103)
movie50.add_child(movie104)
movie50.add_child(movie105)
movie51.add_child(movie106)
movie51.add_child(movie107)
movie52.add_child(movie108)
movie52.add_child(movie109)
movie53.add_child(movie110)
movie53.add_child(movie111)
movie54.add_child(movie112)
movie54.add_child(movie113)
movie55.add_child(movie114)
movie55.add_child(movie115)
movie56.add_child(movie116)
movie56.add_child(movie117)
movie57.add_child(movie118)
movie57.add_child(movie119)
movie58.add_child(movie120)
movie58.add_child(movie121)
movie58.add_child(movie122)
movie59.add_child(movie123)
movie59.add_child(movie124)
movie60.add_child(movie125)
movie60.add_child(movie126)
movie61.add_child(movie127)
movie61.add_child(movie128)
movie62.add_child(movie129)
movie62.add_child(movie130)
movie63.add_child(movie131)
movie63.add_child(movie132)
movie64.add_child(movie133)
movie64.add_child(movie134)
movie65.add_child(movie135)
movie65.add_child(movie136)
movie66.add_child(movie137)
movie66.add_child(movie138)
movie67.add_child(movie139)
movie67.add_child(movie140)
movie68.add_child(movie141)
movie68.add_child(movie142)
movie69.add_child(movie143)
movie69.add_child(movie144)
movie70.add_child(movie145)
movie70.add_child(movie146)
movie71.add_child(movie147)
movie71.add_child(movie148)
movie72.add_child(movie149)
movie72.add_child(movie150)
movie73.add_child(movie151)
movie73.add_child(movie152)
movie74.add_child(movie153)
movie74.add_child(movie154)
movie74.add_child(movie155)
movie75.add_child(movie156)
movie75.add_child(movie157)
movie76.add_child(movie158)
movie76.add_child(movie159)
movie77.add_child(movie160)
movie77.add_child(movie161)
movie78.add_child(movie162)
movie78.add_child(movie163)
movie79.add_child(movie164)
movie79.add_child(movie165)
movie80.add_child(movie166)
movie80.add_child(movie167)
movie81.add_child(movie168)
movie81.add_child(movie169)
movie82.add_child(movie170)
movie82.add_child(movie171)
movie83.add_child(movie172)
movie83.add_child(movie173)
movie84.add_child(movie174)
movie84.add_child(movie175)
movie85.add_child(movie176)
movie85.add_child(movie177)
movie86.add_child(movie178)
movie86.add_child(movie179)
movie87.add_child(movie180)
movie87.add_child(movie181)
movie88.add_child(movie182)
movie88.add_child(movie183)
movie89.add_child(movie184)
movie89.add_child(movie185)
movie90.add_child(movie186)
movie90.add_child(movie187)
movie90.add_child(movie188)
movie91.add_child(movie189)
movie91.add_child(movie190)
movie92.add_child(movie191)
movie92.add_child(movie192)
movie93.add_child(movie193)
movie93.add_child(movie194)
movie94.add_child(movie195)
movie94.add_child(movie196)
movie95.add_child(movie197)
movie95.add_child(movie198)
movie96.add_child(movie199)
movie96.add_child(movie200)
movie97.add_child(movie201)
movie97.add_child(movie202)
movie98.add_child(movie203)
movie98.add_child(movie204)
movie99.add_child(movie205)
movie99.add_child(movie206)
movie100.add_child(movie207)
movie100.add_child(movie208)
movie101.add_child(movie209)
movie101.add_child(movie210)
movie102.add_child(movie211)
movie102.add_child(movie212)
movie103.add_child(movie213)
movie103.add_child(movie214)
movie104.add_child(movie215)
movie104.add_child(movie216)
movie105.add_child(movie217)
movie105.add_child(movie218)
movie106.add_child(movie219)
movie106.add_child(movie220)
movie106.add_child(movie221)
movie107.add_child(movie222)
movie107.add_child(movie223)
movie108.add_child(movie224)
movie108.add_child(movie225)
movie109.add_child(movie226)
movie109.add_child(movie227)
movie110.add_child(movie228)
movie110.add_child(movie229)
movie111.add_child(movie230)
movie111.add_child(movie231)
movie112.add_child(movie232)
movie112.add_child(movie233)
movie113.add_child(movie234)
movie113.add_child(movie235)
movie114.add_child(movie236)
movie114.add_child(movie237)
movie115.add_child(movie238)
movie115.add_child(movie239)
movie116.add_child(movie240)
movie116.add_child(movie241)
movie117.add_child(movie242)
movie117.add_child(movie243)
movie118.add_child(movie244)
movie118.add_child(movie245)
movie119.add_child(movie246)
movie119.add_child(movie247)
movie120.add_child(movie248)
movie120.add_child(movie249)
movie121.add_child(movie250)


criteria = []
genres = []
ratings = []
low = 0
high = 0

def Welcome():
    print("""
    ------------------------------------------------------------------------------------------
 _______  __       __    ______  __  ___ .______    __    ______  __  ___    
|   ____||  |     |  |  /      ||  |/  / |   _  \  |  |  /      ||  |/  /    
|  |__   |  |     |  | |  ,----'|  '  /  |  |_)  | |  | |  ,----'|  '  /     
|   __|  |  |     |  | |  |     |    <   |   ___/  |  | |  |     |    <      
|  |     |  `----.|  | |  `----.|  .  \  |  |      |  | |  `----.|  .  \     
|__|     |_______||__|  \______||__|\__\ | _|      |__|  \______||__|\__\   
    (\____/)
     (_oo_)
       (O)
     __||__    \)
  []/______\[] /
  / \______/ \/
 /    /__\
(\   /____\
 """)
    typingPrint("Hello my name is Zippi! Welcome to FlickPick, the movie recommending software that chooses the right movie for you!")
    time.sleep(1)
    welcome_answer = input(" Before we begin, can you start by telling me your name? Type your name here: ")
    typingPrint("\nHi " + welcome_answer + ", it's great to meet you! Let's get started on finding your ideal movie. Did you know we have 250 of the best movies available for recommendation?")
    print("\n------------------------------------------------------------------------------")

def questions():
    global movie1
    global genres
    global ratings
    global low
    global high
    age = input(rating1.question)
    if age == "A" or age == "a":
        criteria.append("17 years and older")
        ratings.append("R")
        ratings.append("PG-13")
        ratings.append("PG")
        ratings.append("G")
    elif age == "B" or age == "b":
        criteria.append("between 16 to 13 years old")
        ratings.append("PG-13")
        ratings.append("PG")
        ratings.append("G")
    elif age == "C" or age == "c":
        criteria.append("between 12 to 8 years old")
        ratings.append("PG")
        ratings.append("G")
    elif age == "D" or age == "d":
        criteria.append("under 8 years old")
        ratings.append("G")
    else:
        typingPrint("Whoops that wasn't a valid answer, please type the corresponding letter for your answer")
        print("\n-------------------------------------------------------------------------")
        del criteria[:]
        questions()
        bfs(movie1, ratings, genres, low, high)
    typingPrint("\nThank you. Processing your answer for your ideal movie. Melting butter for your popcorn.")
    print("\n---------------------------------------------------------------------------")
    how_long = input(times1.question)
    if how_long == "A" or how_long =="a":
        criteria.append("under 1.5 hours")
        low += 0
        high += 90
    elif how_long == "B" or how_long == "b":
        criteria.append("around 2 hours")
        low += 90
        high += 150
    elif how_long == "C" or how_long == "c":
        criteria.append("at least 2.5 hours") 
        low += 151
        high += 1000
    else:
        typingPrint("Whoops that wasn't a valid answer, please type the corresponding letter for your answer")
        print("\n-------------------------------------------------------------------------")
        del criteria[:]
        questions()
        bfs(movie1, ratings, genres, low, high)
    typingPrint("\nThank you. Processing your answer for your ideal movie. Have I mentioned my favorite movie of all time is Terminator!")
    print("\n---------------------------------------------------------------------------")   
    emotion = input(genre1.question)
    if emotion == "A" or emotion == "a":
        typingPrint("\nThank you. Processing your answer for your ideal movie. Did you know that the first movie produced in color was The Wizard of Oz in 1939? ")
        print("\n---------------------------------------------------------------------------")
        emotion2 = input(genre2a.question)
        if emotion2 == "A" or emotion2 == "a":
            genres.append("Animation")
            genres.append("Fantasy")
            genres.append("Sci-Fi")
            genres.append("Western")
        elif emotion2 == "B" or emotion2 == "b":
            genres.append("Comedy")
            genres.append("Family")
            genres.append("Adventure")
            genres.append("Sports")
            genres.append("Music")
        else:
            typingPrint("Whoops that wasn't a valid answer, please type the corresponding letter for your answer")
            print("\n-------------------------------------------------------------------------")
            del criteria[:]
            questions()
            bfs(movie1, ratings, genres, low, high)                 
    elif emotion == "B" or emotion == "b":
        typingPrint("\nThank you. Processing your answer for your ideal movie. Did you know the very first movie theatre was opened in 1896? ")
        print("\n---------------------------------------------------------------------------")
        emotion22 = input(genre2b.question)
        if emotion22 == "A" or emotion22 == "a":
            genres.append("Drama")
            genres.append("Romance")
            typingPrint("\nThank you. Processing your answer for your ideal movie. ")
            print("\n---------------------------------------------------------------------------")
        elif emotion22 == "B" or emotion22 == "b":
             genres.append("War")
             genres.append("Biography")
             genres.append("History")
             typingPrint("\nThank you. Processing your answer for your ideal movie. ")
             print("\n---------------------------------------------------------------------------")
        else:
                typingPrint("Whoops that wasn't a valid answer, please type the corresponding letter for your answer")
                print("\n-------------------------------------------------------------------------")
                del criteria[:]
                questions()
                bfs(movie1, ratings, genres, low, high)
        emotion3 = input(genre2bb.question)
        if emotion3 == "A" or emotion3 == "a":
                genres.append("Mystery")
                genres.append("Horror")
                genres.append("Thriller")
                typingPrint("\nThank you. Processing your answer for your ideal movie. ")
                print("\n---------------------------------------------------------------------------")
        elif emotion3 == "B" or emotion3 == "b":
                genres.append("Action")
                genres.append("Crime")
                typingPrint("\nThank you. Processing your answer for your ideal movie. ")  
        else:
            typingPrint("Whoops that wasn't a valid answer, please type the corresponding letter for your answer")
            print("\n-------------------------------------------------------------------------")
            del criteria[:]
            questions()
            bfs(movie1, ratings, genres, low, high)
    criteria_statement = ("\nThe youngest member of my group is " + str(criteria[0]) + "," + " I would prefer a movie " + str(criteria[1]) + " long, and I'd like a film in one of the following genres: " + "\n" + str(genres)) 
    print("\n---------------------------------------------------------------------------")
    typingPrint("\nDoes this look like the type of movie you're looking for?")
    typingPrint(criteria_statement)
    answer = input("\nType Y if you're happy with this criteria, otherwise type anything else to startover. Type Here: ")
    if answer == "Y" or answer == "y":
        bfs(movie1, ratings, genres, low, high)
    else:
        questions()
        bfs(movie1, ratings, genres, low, high)

def bfs(root, target1, target2, target3, target4):
    path_queue = deque()
    initial_path = [root]
    path_queue.appendleft(initial_path)
    while path_queue:
        current_path = path_queue.pop()
        current_node = current_path[-1]
        for ratings in target1:
            if ratings == current_node.rating:
                for genres in target2:
                    if genres in current_node.genre:
                        if target3 < int(current_node.duration) and int(current_node.duration) < target4:
                            typingPrint("\n\n""Here's a movie I think you might enjoy: ")
                            print("\n\n",current_node.title,":",current_node.topic)
                            like = input("\nWhat do you think? Are you happy with your recommendation, or would you like a new selection? If you'd like a new movie recommendation, type Y, otherwise type any other letter. Type Here: ")
                            if like == "Y" or like == "y":
                                continue
                            else:
                                print("Enjoy your movie! Thanks for choosing FlickPick")
                                quit()
        for child in current_node.children:
            new_path = current_path[:]
            new_path.append(child)
            path_queue.appendleft(new_path)
    print("Sorry we couldn't find a movie matching your criteria")


def FlickPick():
    Welcome()
    questions()
    

FlickPick()